name: Creating docker image and running trivy scan

on:
 workflow_dispatch:

jobs:
  building-docker-image:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
       docker build -t my-image:v1 .

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@v0.35.0
      with:
       image-ref: "."
       scan-type: 'fs'
       format: 'table'

       
