name: Scanning Source code using Semgrep

on:
 workflow_dispatch:

jobs:
 semgrep-scan:
  runs-on: ubuntu-latest
  container:
    image: semgrep/semgrep
  steps:
    - name: Checkout Source code
      uses: actions/checkout@v4

    - name: Run semgrep security scan
      run: |
       semgrep scan --config=p/security-audit --config=p/python --config=p/owasp-top-ten --include='app.py' || true
        
