name: Scanning Source code using Semgrep

on:
 workflow_dispatch:

jobs:
 semgrep-scan:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Source code
      uses: actions/checkout@v4

    - name: Run semgrep security scan
      uses: semgrep/github-action@v1
      with:
       config: 'p/security-audit'
       auditOnInvalidConfig: true
        
