name: this is a test workflow

on:
  push:
   branches:
     - main

jobs:
  check-build:
   runs-on: ubuntu-latest
   steps:
    - name: print system info
      run: |
       echo "the current working dir is: $(pwd) "
       date
       hostname
       cat /etc/passwd
       echo "finished." 
